version: "3.9"

services:
  reviewservice:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      CONFIG_PATH: /app/conf/conf.env
      MAILER_CONFIG_PATH: /app/conf/mailerconfig.env
      REDIS_PASSWORD: ^G#z2v!QeA9pL1uN@k8rS
    networks:
      - app-network
    dns:
      - "8.8.8.8"  
      - "8.8.4.4"

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: P0stgr3sS3cur3
      POSTGRES_DB: authservice
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres_user -d authservice"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  redis:
    image: redis:7
    command: redis-server --requirepass "^G#z2v!QeA9pL1uN@k8rS"
    environment:
      - REDIS_PASSWORD=^G#z2v!QeA9pL1uN@k8rS
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
