FROM golang:1.23 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build \
    -ldflags="-w -s" -o notification_service ./cmd

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/notification_service .

COPY conf /app/conf

CMD ["./notification_service"]
